#!/bin/bash
#
# righttoprivacy[at]tutanota.com
# https://buymeacoffee.com/politictech/posts (public blog)
#

# VARIABLES
# $i2prouterstart should be command for starting i2p (whichever fork / version)
# $i2prouterstop should be command for stopping i2p (whichever version you use)
i2prouterstart="/home/$USER/i2p/i2prouter start"		# CHANGE THIS IF NEEDED TO MEET ANY I2PROUTER START COMMAND
i2pprofile="I2P Browsing" 	# Change to I2P profile name	# CHANGE IF NEEDED TO MEET STOP I2PROUTER COMMAND
i2prouterstop="/home/$USER/i2p/i2prouter stop"

trap "$i2prouterstop" EXIT

starti2p() {
	echo -e "STARTING I2P ROUTER...\n"
	bash $i2prouterstart
}

starti2p &
sleep 8		# delay for slower devices compatibility

firejail librewolf -P "$i2pprofile" --new-tab https://127.0.0.1:7667
