#!/bin/bash
#
# righttoprivacy[at]tutanota.com
# https://buymeacoffee.com/politictech/posts (public blog)
#

# VARIABLES
i2prouterstart="/home/$USER/i2p/i2prouter start"
i2pprofile="I2P Browsing" 	# Change to I2P profile name
i2prouterstop="/home/$USER/i2p/i2prouter stop"

trap "$i2prouterstop" EXIT

starti2p() {
	echo -e "STARTING I2P ROUTER...\n"
	bash $i2prouterstart
}

starti2p &
sleep 8		# delay for slower devices compatibility

firejail librewolf -P "$i2pprofile" --new-tab https://127.0.0.1:7667
