// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1675448396);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1675491626);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1675452236);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 1675408959);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1675448516);
user_pref("browser.bookmarks.addedImportButton", true);
user_pref("browser.bookmarks.editDialog.confirmationHintShowCount", 3);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.contentblocking.category", "strict");
user_pref("browser.discovery.containers.enabled", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.avif", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.webp", true);
user_pref("browser.migration.version", 128);
user_pref("browser.newtabpage.activity-stream.impressionId", "{114c6ec5-f706-4f6a-b37a-7edf64f3ad11}");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"ids\":[\"bookmark\"],\"idsInUrlbar\":[\"bookmark\"],\"idsInUrlbarPreProton\":[],\"version\":1}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.policies.applied", true);
user_pref("browser.policies.runOncePerModification.addSearchEngines", "/S92rzfUdA8IqLNkEq93Ow==");
user_pref("browser.policies.runOncePerModification.extensionsInstall", "[\"https://addons.mozilla.org/firefox/downloads/latest/ublock-origin/latest.xpi\"]");
user_pref("browser.policies.runOncePerModification.extensionsUninstall", "[\"google@search.mozilla.org\",\"bing@search.mozilla.org\",\"amazondotcom@search.mozilla.org\",\"ebay@search.mozilla.org\",\"twitter@search.mozilla.org\"]");
user_pref("browser.policies.runOncePerModification.removeSearchEngines", "[\"Google\",\"Bing\",\"Amazon.com\",\"eBay\",\"Twitter\"]");
user_pref("browser.policies.runOncePerModification.setDefaultSearchEngine", "DuckDuckGo");
user_pref("browser.proton.toolbar.version", 3);
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1675450010934");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1675471610934");
user_pref("browser.startup.couldRestoreSession.count", 1);
user_pref("browser.startup.lastColdStartupCheck", 1675491598);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"save-to-pocket-button\",\"downloads-button\",\"fxa-toolbar-menu-button\",\"ublock0_raymondhill_net-browser-action\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"import-button\",\"personal-bookmarks\"]},\"seen\":[\"developer-button\",\"ublock0_raymondhill_net-browser-action\"],\"dirtyAreaCache\":[\"nav-bar\",\"PersonalToolbar\",\"toolbar-menubar\",\"TabsToolbar\"],\"currentVersion\":17,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "DuckDuckGo");
user_pref("distribution.iniFile.exists.appversion", "104.0.2");
user_pref("distribution.iniFile.exists.value", true);
user_pref("distribution.io.gitlab.librewolf-community.bookmarksProcessed", true);
user_pref("dom.forms.autocomplete.formautofill", true);
user_pref("dom.push.userAgentID", "60b7fea769a14d3391c8a6c21d54ad67");
user_pref("dom.security.https_only_mode", false);
user_pref("dom.security.https_only_mode_ever_enabled", true);
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 35);
user_pref("extensions.lastAppBuildId", "20220908194232");
user_pref("extensions.lastAppVersion", "104.0.2");
user_pref("extensions.lastPlatformVersion", "104.0.2");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.pictureinpicture.enable_picture_in_picture_overrides", true);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.enable_shims", true);
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.uBlock0@raymondhill.net", true);
user_pref("extensions.webextensions.uuids", "{\"formautofill@mozilla.org\":\"b2e3ab65-dd74-449d-970a-47c9a77aae5e\",\"pictureinpicture@mozilla.org\":\"0029247b-cc82-4232-8ac6-9491df42bc6a\",\"screenshots@mozilla.org\":\"069e95d5-7c02-466b-8047-5c33436a8755\",\"webcompat@mozilla.org\":\"3a011bb4-ca4f-47d4-be1d-c32b65a52579\",\"default-theme@mozilla.org\":\"dcb87b4b-14d8-4d05-b43f-c7b26c91591a\",\"addons-search-detection@mozilla.com\":\"a24a7f30-48ab-4d87-86a3-e7e21be5565d\",\"wikipedia@search.mozilla.org\":\"c6abca08-d65d-49da-b45d-231dfb2848bb\",\"ddg@search.mozilla.org\":\"1b841ee3-e4fa-454c-95a6-288eb4f94d49\",\"uBlock0@raymondhill.net\":\"63dd26b4-7c9b-4260-a591-8215b43c18a1\"}");
user_pref("fission.experiment.max-origins.last-disqualified", 0);
user_pref("fission.experiment.max-origins.last-qualified", 1673306975);
user_pref("fission.experiment.max-origins.qualified", true);
user_pref("gecko.handlerService.defaultHandlersVersion", 1);
user_pref("gfx.blacklist.webrender", 4);
user_pref("gfx.blacklist.webrender.failureid", "FEATURE_FAILURE_DDX_INTEL");
user_pref("idle.lastDailyNotification", 1675449016);
user_pref("intl.accept_languages", "en-US, en");
user_pref("javascript.use_us_english_locale", true);
user_pref("media.gmp-manager.buildID", "20220908194232");
user_pref("media.gmp-manager.lastCheck", 1675448977);
user_pref("media.gmp-manager.lastEmptyCheck", 1675448977);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("media.peerconnection.ice.proxy_only", true);
user_pref("network.http.referer.disallowCrossSiteRelaxingDefault.top_navigation", true);
user_pref("network.proxy.backup.ssl", "127.0.0.1");
user_pref("network.proxy.backup.ssl_port", 4444);
user_pref("network.proxy.http", "127.0.0.1");
user_pref("network.proxy.http_port", 4444);
user_pref("network.proxy.share_proxy_settings", true);
user_pref("network.proxy.ssl", "127.0.0.1");
user_pref("network.proxy.ssl_port", 4444);
user_pref("network.proxy.type", 1);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("places.database.lastMaintenance", 1675449016);
user_pref("privacy.annotate_channels.strict_list.enabled", true);
user_pref("privacy.history.custom", true);
user_pref("privacy.partition.network_state.ocsp_cache", true);
user_pref("privacy.purge_trackers.date_in_cookie_database", "0");
user_pref("privacy.query_stripping.enabled", true);
user_pref("privacy.query_stripping.enabled.pbmode", true);
user_pref("privacy.sanitize.pending", "[]");
user_pref("privacy.trackingprotection.enabled", true);
user_pref("privacy.trackingprotection.socialtracking.enabled", true);
user_pref("privacy.userContext.newTabContainerOnLeftClick.enabled", true);
user_pref("security.sandbox.content.tempDirSuffix", "96272574-ddb9-4c2c-877f-7a7f592758e5");
user_pref("services.sync.engine.addresses.available", true);
user_pref("storage.vacuum.last.index", 1);
user_pref("storage.vacuum.last.places.sqlite", 1673314644);
user_pref("toolkit.startup.last_success", 1675491594);
user_pref("toolkit.telemetry.cachedClientID", "a0235bec-ea16-4ad5-a18d-ebcdb53bda54");
